from django.urls import path, re_path

from . import views


app_name = "academy"


urlpatterns = [
    path("", views.index, name="index"),
    path("index.html", views.index, name="index-file"),
    path("frontend-auth.js", views.frontend_auth_script, name="frontend-auth-script"),
    re_path(r"^media/course-assets/(?P<asset_path>.+)$", views.course_asset_media, name="course-asset-media"),
    path("register", views.public_register, name="register"),
    path("login", views.public_login, name="login"),
    path("refresh-token", views.public_refresh_token, name="refresh-token"),
    path("forgot-password", views.public_forgot_password, name="forgot-password"),
    path("reset-password", views.public_reset_password, name="reset-password"),
    path("verify-email", views.public_verify_email, name="verify-email"),
    path("2fa/verify", views.auth_two_factor_verify, name="two-factor-verify-root"),
    path("profile", views.profile_detail, name="profile"),
    path("profile/update", views.profile_update, name="profile-update-root"),
    path("change-password", views.change_password, name="change-password-root"),
    path("logout", views.auth_logout, name="logout-root"),
    path("users", views.admin_users, name="users-root"),
    path("users/suspend", views.admin_users_suspend, name="users-suspend-root"),
    path("users/verify", views.admin_users_verify, name="users-verify-root"),
    path("users/change-role", views.admin_users_change_role, name="users-change-role-root"),
    path("api/health", views.health, name="health"),
    path("api/register", views.public_register, name="public-register"),
    path("api/login", views.public_login, name="public-login"),
    path("api/refresh-token", views.public_refresh_token, name="public-refresh-token"),
    path("api/forgot-password", views.public_forgot_password, name="public-forgot-password"),
    path("api/reset-password", views.public_reset_password, name="public-reset-password"),
    path("api/verify-email", views.public_verify_email, name="public-verify-email"),
    path("api/2fa/verify", views.auth_two_factor_verify, name="public-two-factor-verify"),
    path("api/profile", views.profile_detail, name="profile-detail"),
    path("api/profile/update", views.profile_update, name="profile-update"),
    path("api/change-password", views.change_password, name="change-password"),
    path("api/logout", views.auth_logout, name="public-logout"),
    path("api/users", views.admin_users, name="admin-users"),
    path("api/users/suspend", views.admin_users_suspend, name="admin-users-suspend"),
    path("api/users/verify", views.admin_users_verify, name="admin-users-verify"),
    path("api/users/change-role", views.admin_users_change_role, name="admin-users-change-role"),
    path("api/auth/login", views.auth_login, name="auth-login"),
    path("api/auth/signup", views.auth_signup, name="auth-signup"),
    path("api/auth/refresh", views.auth_refresh, name="auth-refresh"),
    path("api/auth/2fa/verify", views.auth_two_factor_verify, name="auth-two-factor-verify"),
    path("api/auth/verify-email/request", views.auth_verify_email_request, name="auth-verify-email-request"),
    path("api/auth/verify-email/confirm", views.auth_verify_email_confirm, name="auth-verify-email-confirm"),
    path("api/auth/me", views.auth_me, name="auth-me"),
    path("api/auth/logout", views.auth_logout, name="auth-logout"),
    path("api/auth/oauth/start", views.auth_oauth_start, name="auth-oauth-start"),
    path("api/auth/password/reset-request", views.auth_password_reset_request, name="auth-password-reset-request"),
    path("api/auth/password/reset-confirm", views.auth_password_reset_confirm, name="auth-password-reset-confirm"),
    path("api/newsletter/subscribe", views.newsletter_subscribe, name="newsletter-subscribe"),
    path("api/enrollments/progress", views.enrollment_progress, name="enrollment-progress"),
    path("api/enrollments", views.enrollments, name="enrollments"),
    path("api/wishlist", views.wishlist, name="wishlist"),
    path("api/ai/tutor", views.ai_tutor, name="ai-tutor"),
    path("api/courses/share", views.course_share, name="course-share"),
    path("api/gifts", views.gifts, name="gifts"),
    path("api/coupons/validate", views.coupon_validate, name="coupon-validate"),
    path("api/questions", views.lesson_questions, name="lesson-questions"),
    path("api/questions/completion", views.question_completion, name="question-completion"),
    path("api/notes", views.notes, name="notes"),
    path("api/notebook/notes", views.notebook_notes, name="notebook-notes"),
    path("api/notebook/attachments", views.notebook_attachments, name="notebook-attachments"),
    path("api/assignments", views.assignments, name="assignments"),
    path("api/notifications", views.notifications, name="notifications"),
    path("api/instructor/courses/drafts", views.instructor_drafts, name="instructor-drafts"),
    path("api/instructor/courses", views.instructor_courses, name="instructor-courses"),
    path("api/instructor/courses/assets", views.instructor_course_assets, name="instructor-course-assets"),
    path("api/instructor/courses/thumbnail", views.instructor_thumbnail, name="instructor-thumbnail"),
    path("api/dashboard/tab", views.dashboard_tab, name="dashboard-tab"),
    path("api/certificates/share", views.certificate_share, name="certificate-share"),
    path("api/certificates/preview", views.certificate_preview, name="certificate-preview"),
    path("api/categories", views.course_categories, name="course-categories"),
    path("api/courses/search", views.course_content_search, name="course-content-search"),
    path("api/courses/<slug:course_id>/resources", views.course_resources, name="course-resources"),
    path("api/courses/<slug:course_id>", views.course_detail, name="course-detail"),
    path("api/courses", views.course_list, name="course-list"),
    re_path(r"^api/.*$", views.api_not_found, name="api-not-found"),
]
