# Generated by Django 5.2.13 on 2026-05-08 18:20

import accounts.managers
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, help_text='Optional public handle. Email remains the primary login credential.', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters, numbers, underscores, and dots.', regex='^[A-Za-z0-9_.]+$')])),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('support', 'Support')], db_index=True, default='student', max_length=24)),
                ('avatar', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('is_email_verified', models.BooleanField(db_index=True, default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], db_index=True, default='pending_verification', max_length=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('date_joined', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined', 'email'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
