# Generated by Django 5.2.13 on 2026-05-08 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    StudentProfile = apps.get_model("accounts", "StudentProfile")
    InstructorProfile = apps.get_model("accounts", "InstructorProfile")

    for user in User.objects.all().iterator():
        StudentProfile.objects.get_or_create(user=user)
        if user.role == "instructor":
            InstructorProfile.objects.get_or_create(user=user)


def reverse_create_profiles_for_existing_users(apps, schema_editor):
    StudentProfile = apps.get_model("accounts", "StudentProfile")
    InstructorProfile = apps.get_model("accounts", "InstructorProfile")
    StudentProfile.objects.all().delete()
    InstructorProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('biography', models.TextField(blank=True)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('published_courses_count', models.PositiveIntegerField(default=0)),
                ('total_students_taught', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('teaching_statistics', models.JSONField(blank=True, default=dict)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_verified_instructor', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_streak_days', models.PositiveIntegerField(default=0)),
                ('completed_courses_count', models.PositiveIntegerField(default=0)),
                ('current_courses_count', models.PositiveIntegerField(default=0)),
                ('saved_courses_count', models.PositiveIntegerField(default=0)),
                ('average_progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('total_learning_minutes', models.PositiveIntegerField(default=0)),
                ('learning_statistics', models.JSONField(blank=True, default=dict)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, reverse_create_profiles_for_existing_users),
    ]
