# Generated by Django 5.2.13 on 2026-05-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated_sort', 'title'], 'permissions': [('manage_course_students', 'Can manage enrolled students for owned courses'), ('view_course_analytics', 'Can view instructor course analytics'), ('moderate_courses', 'Can moderate and review course catalog content'), ('configure_platform', 'Can configure platform settings')]},
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='action',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('refresh', 'Refresh'), ('refresh.reuse_detected', 'Refresh Reuse Detected'), ('logout', 'Logout'), ('verify_email.request', 'Verify Email Request'), ('verify_email.confirm', 'Verify Email Confirm'), ('password_change', 'Password Change'), ('password_reset.request', 'Password Reset Request'), ('password_reset.confirm', 'Password Reset Confirm')], max_length=64),
        ),
    ]
