# Generated by Django 5.2.13 on 2026-05-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_course_options_alter_authauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authauditlog',
            name='action',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('two_factor.challenge', 'Two-Factor Challenge'), ('two_factor.verify', 'Two-Factor Verify'), ('two_factor.failed', 'Two-Factor Failed'), ('refresh', 'Refresh'), ('refresh.reuse_detected', 'Refresh Reuse Detected'), ('logout', 'Logout'), ('verify_email.request', 'Verify Email Request'), ('verify_email.confirm', 'Verify Email Confirm'), ('password_change', 'Password Change'), ('password_reset.request', 'Password Reset Request'), ('password_reset.confirm', 'Password Reset Confirm'), ('admin.user_suspend', 'Admin User Suspend'), ('admin.user_verify', 'Admin User Verify'), ('admin.user_change_role', 'Admin User Change Role')], max_length=64),
        ),
    ]
