# Generated by Django 5.2.13 on 2026-05-08 20:59

from django.db import migrations


def backfill_course_structure(apps, schema_editor):
    Course = apps.get_model("academy", "Course")
    CourseCategory = apps.get_model("academy", "CourseCategory")
    CourseModule = apps.get_model("academy", "CourseModule")
    CourseLesson = apps.get_model("academy", "CourseLesson")
    Enrollment = apps.get_model("academy", "Enrollment")

    for index, course in enumerate(Course.objects.all().order_by("category", "title"), start=1):
        category, _created = CourseCategory.objects.get_or_create(
            slug=course.category,
            defaults={
                "code": (course.mark or course.category[:8] or "CR")[:8],
                "label": course.track or course.category.replace("-", " ").title(),
                "badge_class": course.badge_class,
                "gradient": course.gradient,
                "description": f"{course.track or course.category} learning path on SkillForge.",
                "sort_order": index,
                "is_active": True,
                "requirements": course.requirements,
                "learn": course.learn,
                "resources": course.resources,
                "qa": course.qa,
            },
        )
        course.category_ref = category
        course.save(update_fields=["category_ref"])

        for module_index, raw_module in enumerate(course.modules or [], start=1):
            module, _module_created = CourseModule.objects.get_or_create(
                course=course,
                position=module_index,
                defaults={
                    "title": str(raw_module.get("title", f"Module {module_index}")).strip() or f"Module {module_index}",
                    "summary": str(raw_module.get("summary", "") or "").strip(),
                    "duration_label": str(raw_module.get("duration", "") or "").strip(),
                    "is_published": True,
                },
            )
            module.title = str(raw_module.get("title", f"Module {module_index}")).strip() or f"Module {module_index}"
            module.summary = str(raw_module.get("summary", "") or "").strip()
            module.duration_label = str(raw_module.get("duration", "") or "").strip()
            module.is_published = True
            module.save(update_fields=["title", "summary", "duration_label", "is_published", "updated_at"])

            for lesson_index, raw_lesson in enumerate(raw_module.get("lessons", []) or [], start=1):
                lesson_key = str(raw_lesson.get("id", f"{course.slug}-m{module_index}-l{lesson_index}")).strip().lower()
                lesson, _lesson_created = CourseLesson.objects.get_or_create(
                    lesson_key=lesson_key,
                    defaults={
                        "module": module,
                        "title": str(raw_lesson.get("title", f"Lesson {lesson_index}")).strip() or f"Lesson {lesson_index}",
                        "summary": str(raw_lesson.get("summary", "") or "").strip(),
                        "duration_label": str(raw_lesson.get("duration", "") or "").strip(),
                        "content_type": str(raw_lesson.get("type", "video")).strip().lower() or "video",
                        "position": lesson_index,
                        "is_free_preview": bool(raw_lesson.get("free", False)),
                        "is_published": True,
                        "asset_url": str(raw_lesson.get("assetUrl", "") or "").strip(),
                        "metadata": {"done": bool(raw_lesson.get("done", False))},
                    },
                )
                lesson.module = module
                lesson.title = str(raw_lesson.get("title", f"Lesson {lesson_index}")).strip() or f"Lesson {lesson_index}"
                lesson.summary = str(raw_lesson.get("summary", "") or "").strip()
                lesson.duration_label = str(raw_lesson.get("duration", "") or "").strip()
                lesson.content_type = str(raw_lesson.get("type", "video")).strip().lower() or "video"
                lesson.position = lesson_index
                lesson.is_free_preview = bool(raw_lesson.get("free", False))
                lesson.is_published = True
                lesson.asset_url = str(raw_lesson.get("assetUrl", "") or "").strip()
                lesson.metadata = {"done": bool(raw_lesson.get("done", False))}
                lesson.save(
                    update_fields=[
                        "module",
                        "title",
                        "summary",
                        "duration_label",
                        "content_type",
                        "position",
                        "is_free_preview",
                        "is_published",
                        "asset_url",
                        "metadata",
                        "updated_at",
                    ]
                )

        first_lesson = CourseLesson.objects.filter(module__course=course).order_by("module__position", "position", "pk").first()
        if first_lesson:
            Enrollment.objects.filter(course=course, current_lesson__isnull=True, progress_percent__gt=0).update(current_lesson=first_lesson)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_coursecategory_courselesson_enrollment_completed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_course_structure, noop_reverse),
    ]
